# language: r
# sudo: false
# cache: packages
# dist: trusty

# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
warnings_are_errors: false
install:
  - Rscript Installations.R

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'

VignetteBuilder: knitr
